# Generated by Django 4.1.2 on 2022-10-28 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_collection_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
