# Generated by Django 4.1.2 on 2022-10-28 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_reviews_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='data',
            new_name='date',
        ),
    ]
